### ISSUE TITLE
Is there a way to do a where on a class type

### ISSUE THREAD

**Issue by mdebellefeuille** [xjodoin/torpedoquery#39]
given hierarchy
E reference A
B extends A
C extends A
D extends A

Is there a way to create a query that will scope on a subclass

select * from E e 
inner join A a 
where a.class = B or a.class = C

tried doing where(a.getClass) .eq(B.class)... but doesn't compile

**Comment by xjodoin** [comment]
it worked you must write it like that where(a).eq(B.class)
