### ISSUE TITLE
How to select a POJO with a JPQL query

### ISSUE THREAD

**Issue by dgks0n** [xjodoin/torpedoquery#54]
The entity projection doesn’t fit my use case. Is there an easy option to select POJOs instead of entities?

Like this:

```
TypedQuery<BookValue> q = em.createQuery(
      "SELECT new org.thoughts.on.java.model.BookValue("
      + "b.id, b.title, b.publisher.name) FROM Book b "
      + "WHERE b.id = :id", BookValue.class);
q.setParameter("id", 1L); BookValue b = q.getSingleResult();
```

**Comment by xjodoin** [comment]
for that use case you should use dynamic instantiation
example: 
select(dyn(new ProjectionEntity(param(entity.getCode()), param(entity.getIntegerField()))))
