### ISSUE TITLE
Is there any way to fetch child class?

### ISSUE THREAD

**Issue by dgks0n** [xjodoin/torpedoquery#55]
I have two classes as below:

```
public class User {
    private List<Project> projects = new ArrayList<>();
}

public class Project {
    // do something here
}
```
In repository layer, is there anyway to load an user with its collection similar to `fetch join` in JQL?

**Comment by xjodoin** [comment]
no but you should use entity grah

**Comment by dgks0n** [comment]
Thank you so much.

Is it support MATCH AGAINST functions?

**Comment by xjodoin** [comment]
if the function isn't supporting natively with torpedo you could use Torpedo.function()
